name: Build and Deploy Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Set Date Variable
      id: set_date
      run: |
        echo "::set-output name=date::$(Get-Date -Format 'yyyyMMdd_HHmmss')"

    - name: Create Executable
      run: |
        pyinstaller --onefile --name "MyApp_${{ steps.set_date.outputs.date }}" --windowed main.py

    - name: Move Executable
      run: |
        Move-Item "./dist/MyApp_${{ steps.set_date.outputs.date }}.exe" "./MyApp_${{ steps.set_date.outputs.date }}.exe"

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit executable
      run: |
        git add "MyApp_${{ steps.set_date.outputs.date }}.exe"
        git commit -m "Add generated executable"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
