name: Build and Deploy Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Create Executable
      uses: sayyid5416/pyinstaller@v1
      with:
        python_ver: '3.10'
        spec: 'main.py'
        upload_exe_with_name: 'MyExecutable'
        options: '--onefile, --name "MyApp", --windowed'

    - name: Move Executable
      run: |
        mv ./MyApp.exe ./
    
    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit executable
      run: |
        git add MyApp.exe
        git commit -m "Add generated executable"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PYTHON_EXE_TOKEN }}
